### ISSUE TITLE
M2无法运行

### ISSUE THREAD

**Issue by LingTaixu** [Naruto-Senki/localization#1]
双击时弹出损坏 使用sudo xattr -r -d com.apple.quarantine /Applications/NarutoSenkiV2.app/修复后弹出报错
`
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               NarutoSenkiV2 [55801]
Path:                  /Applications/NarutoSenkiV2.app/Contents/MacOS/NarutoSenkiV2
Identifier:            re.naruto.game
Version:               2.1.4 (6)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-02-27 18:22:51.2744 +0800
OS Version:            macOS 13.1 (22C65)
Report Version:        12
Anonymous UUID:        A9863A9D-44FA-0740-9CB4-F150F2C5C79C

Sleep/Wake UUID:       77CDF0ED-2FF2-44A3-906F-0537FE92AC8C

Time Awake Since Boot: 310000 seconds
Time Since Wake:       17211 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/opt/brotli/lib/libbrotlidec.1.dylib
Referenced from: <6ED981E2-DDAE-36C4-9021-FC4B2E27A900> /Applications/NarutoSenkiV2.app/Contents/MacOS/NarutoSenkiV2
Reason: tried: '/usr/local/opt/brotli/lib/libbrotlidec.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/brotli/lib/libbrotlidec.1.dylib' (no such file), '/usr/local/opt/brotli/lib/libbrotlidec.1.dylib' (no such file), '/usr/local/lib/libbrotlidec.1.dylib' (no such file), '/usr/lib/libbrotlidec.1.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x1019169a8 ???
1   <translation info unavailable>	       0x1019ab91c ???
2   dyld                          	       0x10189ed07 abort_with_payload_wrapper_internal + 82
3   dyld                          	       0x10189ed39 abort_with_payload + 9
4   dyld                          	       0x1018261e1 dyld4::halt(char const*) + 375
5   dyld                          	       0x101823660 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4502
6   dyld                          	       0x101822281 start + 2289

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffeeb614 0x7ff7ffee7000 + 17940
1   runtime                       	    0x7ff7ffef7530 0x7ff7ffee7000 + 66864
2   runtime                       	    0x7ff7ffef8f30 0x7ff7ffee7000 + 73520

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x00000002061ce9d0   x3: 0x0000000000000080
    x4: 0x00000002061ce5d0   x5: 0x0000000000000000   x6: 0x636f6c2f7273752f   x7: 0x000000206f2f6c61
    x8: 0x00000002061ce5d0   x9: 0x0000000000000000  x10: 0x0000000000000080  x11: 0x00000002061ce5d0
   x12: 0x0000000000000080  x13: 0x00000002061ce9d0  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x800000010006bb80  x19: 0x0000000100000000
   x20: 0x00000000000007ff  x21: 0x0000000100070fa0  x22: 0xffffffffffffffff  x23: 0x000000010191697c
   x24: 0x000000010189ed07  x25: 0x0000000101916248  x26: 0x00000001019a9608  x27: 0x0000000000000000
   x28: 0x0000000101885b4a   fp: 0x000000002c000000   lr: 0x00000001019ab91c
    sp: 0x000000010006bb80   pc: 0x00000001019169a8 cpsr: 0x80001000
   far: 0x00000001019ab000  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x10181c000 -        0x1018b3fff dyld (*) <bb7a0970-8c62-3dce-a7a2-5cec9c501f11> /usr/lib/dyld
    0x7ff7ffee7000 -     0x7ff7fff16fff runtime (*) <d592bc4a-4a21-348f-a406-e12f9cd2f27c> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=14.9M resident=0K(0%) swapped_out_or_unallocated=14.9M(100%)
Writable regions: Total=157.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=157.4M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    896K      221 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
VM_ALLOCATE                       15.4M        7 
VM_ALLOCATE (reserved)              24K        1         reserved VM address space (unallocated)
__DATA                             672K        6 
__DATA_CONST                       688K        2 
__DATA_DIRTY                        16K        1 
__LINKEDIT                        3744K        8 
__TEXT                            11.3M        4 
dyld private memory                512K        2 
mapped file                        6.6G       34 
===========                     =======  ======= 
TOTAL                              6.8G      294 
TOTAL, minus reserved VM space     6.8G      294 

-----------
Full Report
-----------

{"app_name":"NarutoSenkiV2","timestamp":"2023-02-27 18:22:51.00 +0800","app_version":"2.1.4","slice_uuid":"6ed981e2-ddae-36c4-9021-fc4b2e27a900","build_version":"6","platform":1,"bundleID":"re.naruto.game","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.1 (22C65)","roots_installed":0,"name":"NarutoSenkiV2","incident_id":"33A47322-9AB5-46D6-99C0-EA227739F5E8"}
{
  "uptime" : 310000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,2",
  "coalitionID" : 71723,
  "osVersion" : {
    "train" : "macOS 13.1",
    "build" : "22C65",
    "releaseType" : "User"
  },
  "captureTime" : "2023-02-27 18:22:51.2744 +0800",
  "incident" : "33A47322-9AB5-46D6-99C0-EA227739F5E8",
  "pid" : 55801,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-02-27 18:22:51.2202 +0800",
  "procStartAbsTime" : 7533923921320,
  "procExitAbsTime" : 7533925205991,
  "procName" : "NarutoSenkiV2",
  "procPath" : "\/Applications\/NarutoSenkiV2.app\/Contents\/MacOS\/NarutoSenkiV2",
  "bundleInfo" : {"CFBundleShortVersionString":"2.1.4","CFBundleVersion":"6","CFBundleIdentifier":"re.naruto.game"},
  "storeInfo" : {"deviceIdentifierForVendor":"6BBF0C34-ADB5-500E-8778-DC430EC6A8A8","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "re.naruto.game",
  "crashReporterKey" : "A9863A9D-44FA-0740-9CB4-F150F2C5C79C",
  "throttleTimeout" : 2147483647,
  "wakeTime" : 17211,
  "sleepWakeUUID" : "77CDF0ED-2FF2-44A3-906F-0537FE92AC8C",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/usr\/local\/opt\/brotli\/lib\/libbrotlidec.1.dylib","Referenced from: <6ED981E2-DDAE-36C4-9021-FC4B2E27A900> \/Applications\/NarutoSenkiV2.app\/Contents\/MacOS\/NarutoSenkiV2","Reason: tried: '\/usr\/local\/opt\/brotli\/lib\/libbrotlidec.1.dylib' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/usr\/local\/opt\/brotli\/lib\/libbrotlidec.1.dylib' (no such file), '\/usr\/local\/opt\/brotli\/lib\/libbrotlidec.1.dylib' (no such file), '\/usr\/local\/lib\/libbrotlidec.1.dylib' (no such file), '\/usr\/lib\/libbrotlidec.1.dylib' (no such file, not in dyld cache)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":4268767,"threadState":{"x":[{"value":6},{"value":1},{"value":8692492752},{"value":128},{"value":8692491728},{"value":0},{"value":7165064483209180463},{"value":139304332385},{"value":8692491728},{"value":0},{"value":128},{"value":8692491728},{"value":128},{"value":8692492752},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041150184320},{"value":4294967296},{"value":2047},{"value":4295430048},{"value":18446744073709551615},{"value":4321274236},{"value":4320783623,"symbolLocation":82,"symbol":"abort_with_payload_wrapper_internal"},{"value":4321272392},{"value":4321875464},{"value":0},{"value":4320680778,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4321884444},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4295408512},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4321274280,"matchesCrashFrame":1},"far":{"value":4321882112}},"frames":[{"imageOffset":4321274280,"region":"Rosetta Runtime Routines","symbolLocation":10664,"imageIndex":0},{"imageOffset":4321884444,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":535815,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":1},{"imageOffset":535865,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":41441,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":30304,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4502,"imageIndex":1},{"imageOffset":25217,"symbol":"start","symbolLocation":2289,"imageIndex":1}]},{"id":4268779,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":17940,"imageIndex":2},{"imageOffset":66864,"imageIndex":2},{"imageOffset":73520,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4320247808,
    "size" : 622592,
    "uuid" : "bb7a0970-8c62-3dce-a7a2-5cec9c501f11",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703127465984,
    "size" : 196608,
    "uuid" : "d592bc4a-4a21-348f-a406-e12f9cd2f27c",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703334383616,
  "size" : 21474836480,
  "uuid" : "16923f88-e9fc-38d2-947c-df242e486636"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=14.9M resident=0K(0%) swapped_out_or_unallocated=14.9M(100%)\nWritable regions: Total=157.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=157.4M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    896K      221 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nVM_ALLOCATE                       15.4M        7 \nVM_ALLOCATE (reserved)              24K        1         reserved VM address space (unallocated)\n__DATA                             672K        6 \n__DATA_CONST                       688K        2 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                        3744K        8 \n__TEXT                            11.3M        4 \ndyld private memory                512K        2 \nmapped file                        6.6G       34 \n===========                     =======  ======= \nTOTAL                              6.8G      294 \nTOTAL, minus reserved VM space     6.8G      294 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {

      },
      "deploymentId" : 240000002
    },
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000022
    }
  ],
  "experiments" : [

  ]
}
}

Model: Mac14,2, BootROM 8419.60.44, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M2, Apple M2, Built-In
Display: Color LCD, spdisplays_2560x1664Retina, Main, MirrorOff, Online
Display: AN-238W03K, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), MirrorOff, Online
Memory Module: LPDDR5, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Sep  3 2022 02:35:52 version 20.10.965.9.8.7.129 FWID 01-b0e84a9b
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB 2.0 Hub
USB Device: Generic Billboard Device
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.
`

**Comment by LingTaixu** [comment]
Mac OS版本13.1

**Comment by real-re** [comment]
bug反馈 可以通过群里 向我发送。
